routes/web.php
<?php

use App\Http\Controllers\MemberController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
	return view('main');
});

Route::get('/member', [MemberController::class, 'index']);

Route::get('/member/login', [MemberController::class, 'login']);

Route::get('/member/register', [MemberController::class, 'register']);

Route::get('/member/profile', [MemberController::class, 'profile']);

Route::get(
	'/dashboard',
	[MemberController::class, 'index']
)
	->name('dashboard')
	->middleware(['auth']);


// -- Admin User Module
Route::resource('admin/user', UserController::class);
Route::resource('admin/role', RoleController::class);

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    //tujuan untuk benarkan column yang boleh diedit di database
    protected $fillable = [
        'name'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        # code...
        return $this->belongsToMany(Role::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;

class MemberController extends Controller
{
    // --- /member
    public function index()
    {
        return view('dashboard');
    }

    // --- /member/profile
    public function profile()
    {
        # code...
        return view('member.profile');
    }

    // --- /member/login
    public function login()
    {
        # code...
        return view('member.login');
    }

    // --- /member/register
    public function register()
    {
        return view('member.register');
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        # code...
        if (!Gate::allows('is-admin')) {
            abort(403);
        }
        $roles = Role::all();
        return view('admin.role.index', ['roles' => $roles]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //

        return view('admin.role.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //

        $data = $request->validate(
            [
                'name' => 'required|min:5|max:100'
            ]
        );

        $role = Role::create($data);

        return redirect('/admin/role')->with('success', "Peranan <b>{$role->name} ({$role->id})</b> telah berjaya disimpan");
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
        return view('admin.role.edit');
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules\Unique;

class UserController extends Controller
{

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        # code...
        if (!Gate::allows('is-admin')) {
            abort(403);
        }
        $users = User::paginate(10);

        return view('admin.user.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //simpan data
        $form_data = $request->validate(
            [
                'name' => 'required|min:5|max:255',
                'email' => 'required|email',
                'password' => 'required|confirmed',
            ]
        );

        $form_data['password'] = Hash::make($form_data['password']);

        $user = User::create($form_data);

        return redirect('admin/user')->with('success', "Pengguna {$user->name} ($user->id) telah ditambah");
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $user = User::find($id);
        $roles = Role::all();

        return view('admin.user.edit', ['user' => $user, 'roles' => $roles]);

        //dd($user);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //

        $user = User::findOrFail($id);

        $form_data = $request->validate(
            [
                'name' => 'required|min:5|max:255',
                'email' => 'required|email',
            ]
        );
        $user->name = $form_data['name'];
        $user->email = $form_data['email'];

        $user->save();

        $user->roles()->sync($request->roles);

        return redirect('admin/user')->with('success', "Pengguna {$user->name} ($id) telah dikemaskini");
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/admin/role/create.blade.php
@extends('layout.private')

@section('content')
<h1 class="h3 mb-2 text-gray-800">Tambah Peranan</h1>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Berikan Nama Untuk Peranan Baru</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('role.store') }}" method="post">
            @csrf
            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}">
                    @error('name')
                    <div class="invalid-feedback"> {{$message}}</div>
                    @enderror
                </div>
            </div>
            <a href="/admin/role" class="btn btn-lg  btn-secondary">Batal</a>
            <button class="btn btn-lg btn-primary" type="submit">Tambah</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/role/index.blade.php
@extends('layout.private')

@section('content')

<div class="d-flex justify-content-between mb-3">
    <h1 class="h3 mb-2 text-gray-800">Senarai Peranan Pengguna</h1>

    <a href="/admin/role/create" class="btn btn-secondary">Tambah Peranan</a>
</div>


@if(session('success'))
<div class="alert alert-success">
    {!! session('success')!!}
</div>
@endif

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Senarai Peranan Pengguna</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>NAMA</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($roles as $role)
                    <tr>
                        <td>{{ $role->id }}</td>
                        <td>{{ $role->name }}</td>
                        <td>
                            <a href="{{ route('role.edit', $role->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                            <form class="d-inline" method="post" action="{{ route('role.destroy', $role->id) }}" onsubmit="return confirm('Are you sure want to delete {{$role->name}} {{$role->id}}')">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm">DELETE</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection

resources/views/admin/user/create.blade.php
@extends('layout.private')

@section('content')
<h1 class="h3 mb-2 text-gray-800">Tambah Pengguna</h1>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tambah Pengguna Baru</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('user.store') }}" method="post">
            @csrf
            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}">
                    @error('name')
                    <div class="invalid-feedback"> {{$message}}</div>
                    @enderror
                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{old('email')}}">
                    @error('email')
                    <div class="invalid-feedback"> {{$message}}</div>
                    @enderror

                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" value="">
                    @error('password')
                    <div class="invalid-feedback"> {{$message}}</div>
                    @enderror

                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Sahkan Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control @error('password_confirmation') is-invalid @enderror" name="password_confirmation" value="">
                    @error('password_confirmation')
                    <div class="invalid-feedback"> {{$message}}</div>
                    @enderror

                </div>
            </div>
            <a href="/admin/user" class="btn btn-lg  btn-secondary">Batal</a>
            <button class="btn btn-lg btn-primary" type="submit">Tambah</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layout.private')

@section('content')
<h1 class="h3 mb-2 text-gray-800">Edit Pengguna</h1>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">{{ $user->name }}</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('user.update', $user->id) }}" method="post">
            @csrf
            @method('put')
            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$user->name) }}">
                    @error('name')
                    <div class="invalid-feedback"> {{$message}}</div>
                    @enderror

                </div>


            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{old('email', $user->email )}}">
                    @error('email')
                    <div class="invalid-feedback"> {{$message}}</div>
                    @enderror

                </div>
            </div>

            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label">Peranan</label>
                <div class="col-sm-10">
                    @foreach($roles as $role)
                    <div class="custom-control custom-checkbox small">

                        <input @if(in_array($role->id,$user->roles->pluck('id')->toArray()))
                        checked
                        @endif

                        type="checkbox" class="custom-control-input" name="roles[]" value="{{$role->id}}" id="role_{{$role->id}}">
                        <label class="custom-control-label" for="role_{{$role->id}}">
                            {{$role->name}}
                        </label>

                    </div>
                    @endforeach
                </div>
            </div>
            <a href="/admin/user" class="btn btn-lg  btn-secondary">Batal</a>
            <button class="btn btn-lg btn-primary" type="submit">Simpan</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layout.private')

@section('content')

<div class="d-flex justify-content-between mb-3">
    <h1 class="h3 mb-2 text-gray-800">Senarai Pengguna</h1>

    <a href="/admin/user/create" class="btn btn-secondary">Tambah Pengguna</a>
</div>


@if(session('success'))
<div class="alert alert-success">
    {{ session('success')}}
</div>
@endif

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Senarai Pengguna</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            {{ $users->links() }}
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>NAMA</th>
                        <th>EMAIL</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>
                            <a href="#" class="btn btn-sm btn-danger">DELETE</a>
                            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $users->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/dashboard.blade.php
@extends ('layout.private')

@section('content')
@if (session('status'))
<div>{{ session('status') }}</div>
@endif

<div>You are logged in!</div>

<form method="POST" action="{{ route('logout') }}">
    @csrf

    <button type="submit">
        {{ __('Logout') }}
    </button>
</form>

<hr>

@if (Laravel\Fortify\Features::enabled(Laravel\Fortify\Features::updateProfileInformation()))
@include('profile.update-profile-information-form')
@endif

@if (Laravel\Fortify\Features::enabled(Laravel\Fortify\Features::updatePasswords()))
@include('profile.update-password-form')
@endif

@if (Laravel\Fortify\Features::enabled(Laravel\Fortify\Features::twoFactorAuthentication()))
@include('profile.two-factor-authentication-form')
@endif
@endsection

resources/views/kelas.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kelas Laravel</title>
</head>

<body>
    <h1>Selamat Datang</h1>

</body>

</html>

resources/views/layout/public.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="/template/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/template/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/template/vendor/jquery/jquery.min.js"></script>
    <script src="/template/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/template/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/template/js/sb-admin-2.min.js"></script>

</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>
    </head>
    <body>
        @yield('content')
    </body>
</html>

resources/views/main.blade.php
@extends ('layout.public')
@section('content')
<h1>Selamat Datang</h1>
<h2>Azhari</h2>

<p>&nbsp;</p>

<a href="/register" class=" btn btn-primary btn-user btn-block">
    Register Account
</a>

<a href="/login" class=" btn btn-secondary btn-user btn-block">
    Login Account
</a>
@endsection

resources/views/member/login.blade.php
@extends ('layout.public')
@section('content')
<div class="text-center">
    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
</div>
<form class="user">
    <div class="form-group">
        <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
    </div>
    <div class="form-group">
        <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
    </div>
    <div class="form-group">
        <div class="custom-control custom-checkbox small">
            <input type="checkbox" class="custom-control-input" id="customCheck">
            <label class="custom-control-label" for="customCheck">Remember
                Me</label>
        </div>
    </div>
    <a href="/member" class="btn btn-primary btn-user btn-block">
        Login
    </a>
    <hr>
    <a href="index.html" class="btn btn-google btn-user btn-block">
        <i class="fab fa-google fa-fw"></i> Login with Google
    </a>
    <a href="index.html" class="btn btn-facebook btn-user btn-block">
        <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
    </a>
</form>
<hr>
<div class="text-center">
    <a class="small" href="forgot-password.html">Forgot Password?</a>
</div>
<div class="text-center">
    <a class="small" href="register.html">Create an Account!</a>
</div>
@endsection

resources/views/member/profile.blade.php
@extends ('layout.private')
@section('content')
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
</div>
@endsection

resources/views/member/register.blade.php
@extends ('layout.public')
@section('content')
<div class="text-center">
    <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
</div>
<form class="user">
    <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
            <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">
        </div>
        <div class="col-sm-6">
            <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name">
        </div>
    </div>
    <div class="form-group">
        <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">
    </div>
    <div class="form-group row">
        <div class="col-sm-6 mb-3 mb-sm-0">
            <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
        </div>
        <div class="col-sm-6">
            <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">
        </div>
    </div>
    <a href="login.html" class="btn btn-primary btn-user btn-block">
        Register Account
    </a>
    <hr>
    <a href="index.html" class="btn btn-google btn-user btn-block">
        <i class="fab fa-google fa-fw"></i> Register with Google
    </a>
    <a href="index.html" class="btn btn-facebook btn-user btn-block">
        <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
    </a>
</form>
<hr>
<div class="text-center">
    <a class="small" href="forgot-password.html">Forgot Password?</a>
</div>
<div class="text-center">
    <a class="small" href="login.html">Already have an account? Login!</a>
</div>
@endsection

resources/views/utama.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<title>Utama</title>
</head>

<body>
    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">About</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                    <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
                </form>

                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2">Login</button>
                    <button type="button" class="btn btn-warning">Sign-up</button>
                </div>
            </div>
        </div>
    </header>
    <div class="container mt-5">
        <div class="row bg-primary">
            <div class="col-md-6 col-lg-3 bg-dark text-light">
                col-md-6 col-lg-3
            </div>
            <div class="col-md-6 col-lg-3 bg-secondary">
                col-md-6 col-lg-3
            </div>
            <div class="col-md-12 col-lg-3 bg-dark text-light">
                col-md-12 col-lg-6
            </div>
        </div>
    </div>
</body>

</html>